### ISSUE TITLE
ReadableStream has already been used

### ISSUE THREAD

**Issue by bossmodex** [elysiajs/elysia-apollo#35]
### What version of Elysia is running?

1.2.8

### What platform is your computer?

Microsoft Windows NT 10.0.19045.0 x64

### What steps can reproduce the bug?

Update elysia from 1.2.6 to 1.2.8

### What do you see instead?

error: ReadableStream has already been used
      at mergeResponseWithSetHeaders (\api\node_modules\elysia\src\adapter\web-standard\handler.ts:238:14)      
      at mapResponse (\api\node_modules\elysia\src\adapter\web-standard\handler.ts:324:16)
      at createNativeStaticHandler (\api\node_modules\elysia\src\adapter\bun\handler.ts:18:19)
      at add (\api\node_modules\elysia\src\index.ts:733:15)
      at get (\api\node_modules\elysia\src\index.ts:3997:8)
      at \api\node_modules\@elysiajs\apollo\dist\index.mjs:33:11

### Additional information

with update elysia 1.2.8 have this error
![webstorm64_7gzli6tF08](https://github.com/user-attachments/assets/59a7495a-a352-4772-b493-1026a4c82253)
![webstorm64_1QlS5Xit70](https://github.com/user-attachments/assets/7444b26b-53e3-43e5-89ce-1be24b457cc0)

when rolling back to 1.2.6 everything works

**Comment by oldmahor** [comment]
The issue is that `app.get` expects a handler function, not a `Response` directly.

```typescript
if (landingPage)
  app.get(path, () => {
    return new Response(landingPage as string, {
      headers: {
        'Content-Type': 'text/html',
      },
    })
  })
```

This should fix the issue. 
Wait for them to update it.

**Comment by Fifixex** [comment]
Hello, I have encountered the same issue and wanted to share more details. Here is a screenshot showing the error in my environment:
![screenshot](https://github.com/user-attachments/assets/5e42d4e8-66d7-4893-ac9c-ab2b75d7e72c)

**Comment by hariangr** [comment]
I am new to elysia and I encountered this
Any update on this?

**Comment by Ianantashrestha** [comment]
Downgrading Elysia to version 1.2.5 worked for me.

**Comment by hariangr** [comment]
> Downgrading Elysia to version 1.2.5 worked for me.

At least for me, this solution doesn't work

**Comment by andymeek** [comment]
Any updates on this bug?
